[package]
name = "validate-witx"
description = "Rust crate used to validate witx syntax"
version = "0.1.0"
authors = ["Fastly <oss@fastly.com>"]
edition = "2018"

[dependencies]
anyhow = "^1.0.40"
witx = "^0.9.0"
